### ISSUE TITLE
How to remove repeatable jobs?

### ISSUE THREAD

**Issue by chrisabrams** [OptimalBits/bull#1005]
## Description
Calling queue.empty() will not remove the repeatable job. I made a repeatable job at cron 1 minute interval, then tried upping it to 5 minutes. The result was that I had two cron jobs: one at the 1 minute interval, the other at the 5 minute interval. I would like to know if there is an API call to remove a repeat/cron so that I can essentially update/change the cron for a job vs having multiple crons for a job.

## Minimal, Working Test code to reproduce the issue.
```js
paymentsQueue.process(function(job){
  // Check payments
});

// Repeat payment job once every day at 3:15 (am)
paymentsQueue.add(paymentsData, {repeat: {cron: '*/1 * * * *'}});
// does not clear the one minute
paymentsQueue.empty()
paymentsQueue.add(paymentsData, {repeat: {cron: '*/5 * * * *'}});
```
Now I have two repeatable jobs, but I only want one.

## Bull version
3.4.3

## Additional information
None.

**Comment by manast** [comment]
You should be able to use https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queueremoverepeatable

**Comment by chrisabrams** [comment]
I'm not sure how I missed that option :O Thanks.

**Comment by PaulGrimshaw** [comment]
You can also use the undocumented `.removeRepeatableByKey(key)` to remove a job by its key

**Comment by stevenolay** [comment]
> removeRepeatableByKey

O.o Where is this located. This might be able to solve my problem. How would I get the key? Would it be the same as the JobId or is this something entirely different?

**Comment by stevenolay** [comment]
I did some playing around. When you supply a jobId to the options like so:
`
    const jobId = "my job id";

    const data {
      key: "val"
    };

    const jobOptions: JobOptions = {
      jobId,
      repeat: {
        cron: `*/2 * * * *`,
        tz: 'America/Los_Angeles'
      }
    };
  
  chronQueue.add(data, jobOptions);
`

As long as the jobId remains the same it maps to the same key in redis. The key in redis is not my provided jobID but an additional job doesn't get created unless the jobId is changed. Would it be save to assume that whatever key generation algorithm being used by bull is using my jobId in the calculations?

The key in redis does not change if i make any changes to the cron string. Only if I make changes to the jobId.

**Comment by manast** [comment]
@stevenolay you could get the key by for example calling ```getRepeatableJobs```

**Comment by stevenolay** [comment]
@manast  Well, using getRepeatableJobs would not be good for me because am expecting on the order of thousands of repeatable jobs. Iterating across those in memory would be less than ideal.

**Comment by stevenolay** [comment]
@manast I tried using one of the keys from getRepeatableJobs and passed it to removeRepeatableByKey however, the job was not removed :(

**Comment by stevenolay** [comment]
@manast  I took a look at the payload for getRepeatableJobs and looked though the helper functions for repeat jobs in repeatable.js and was able to figure out how to construct jobKeys dynamically. 

One thing I noticed is even if the jobs are removed and getRepeatableJobs returns a empty list. The jobs still appear in redis if i call "keys *" in the redis-cli. Would you have any insights on this?

**Comment by manast** [comment]
getRepeatableJobs returns only the canonical job so to speak, the real jobs that have been processed will stay in the queue unless removed.

**Comment by eltronix** [comment]
Hey @manast, could you kindly provide an example usage of:
https://github.com/OptimalBits/bull/blob/master/REFERENCE.md#queueremoverepeatable

I can't get it to work for me even though I'm resuing the same options object.

`.removeRepeatableByKey(key)` seems to work fine.

**Comment by ganeshcse2991** [comment]
When i tried using this method - removeRepeatableByKey I am getting removeRepeatableByKey is not a function error.
queue_1.taskQueue.removeRepeatableByKey is not a function

I am not able to remove my repeatable job by taskQueue.removeRepeatable('task', { cron: '0 47 6 * * 4' }); this too

JSON of the JOB:
{ id: "repeat:09854c8042eced1337a7d8eec9357528:1552526220000", name: "task", data: { eventName: "test", parameters: [ { my_JSON }, { my_JSON } ] }, opts: { repeat: { count: 1, cron: "0 47 6 * * 4", jobId: "myJobId" }, jobId: "repeat:09854c8042eced1337a7d8eec9357528:1552526220000", delay: 603096068, timestamp: 1551923123932, prevMillis: 1552526220000, priority: 1, attempts: 3, removeOnComplete: true, backoff: { type: "fixed", delay: 3 }, timeout: 60000 }, progress: 0, delay: 603096068, timestamp: 1551923123932, attemptsMade: 0, stacktrace: [ ], returnvalue: null, finishedOn: null, processedOn: null }

**Comment by manast** [comment]
@ganeshcse2991 if you provide a code snipped that reproduces the error we can help you much faster.

**Comment by manast** [comment]
@eltronix https://github.com/OptimalBits/bull/blob/develop/test/test_repeat.js#L362

**Comment by ganeshcse2991** [comment]
@manast  sure the following is my code:

```
export const addTaskCard = function (queue_options) {
  logger.info('Inside Task Queue Addition Block');
  try {
    if (!isNullOrUndefined(queue_options)) {
      let jobOptions = {
        priority: queue_options.priority,
        repeat: { cron: '0 47 6 * * 4' },
        attempts: 3,
        removeOnComplete: true,
        jobId: queue_options.job_id,
        backoff: 3,
        timeout: 60000,
      };
      taskQueue.add('task', queue_options.data, jobOptions);
    }
  }
  catch (error) {
    logger.error(error)
    logger.error("Job Not added to the queue")
  }
};

let processTaskQueue = function () {
  logger.info('***********************Processing Task Queue***********************');
  taskExecutor.process('task', 100, function (job, done) {
    eventEmitter.emit(job.data.eventName, job.data.parameters);
    done();
  });

  taskExecutor.on('completed', function (job, result) {
    logger.info('Task Created for job: ' + job.id + ' and result is: ' + result);
  });

  taskExecutor.on('error', function (job, result) {
    logger.error('Error Occured while processing the Job in the Queue');
    logger.error(result);
  });
};

export async function removeJob(jobId, cron) {
  console.log("Inside get job")
  console.log(jobId);
  console.log(cron)
  try {
    let job = await taskQueue.removeRepeatable('task', {cron : '0 47 6 * * 4'});
    //let jobs = await taskQueue.getRepeatableJobs();
    console.log(job)
    //let job = await taskQueue.removeRepeatableByKey(jobs[0].key);

  } catch (error) {
    //console.log(error);
  }
}

processTaskQueue();
```

I tried both the moethods removeRepeatableByKey and removeRepeatable. removeRepeatableByKey is giving me an error as 'is not a function'. 

```
queue_1.taskQueue.removeRepeatableByKey is not a function

```

How I create my task queue: 
```
export const taskQueue = new Queue('task', appConfig[process.env.NODE_ENV].redis);
export const taskExecutor = new Queue('task', appConfig[process.env.NODE_ENV].redis);
```

**Comment by ganeshcse2991** [comment]
@eltronix  Can you give and example of removeRepeatableByKey. Its throwing me an error as 

`queue_1.taskQueue.removeRepeatableByKey  is not a function`

**Comment by eltronix** [comment]
@ganeshcse2991 I currently use this to remove all my repeatable jobs. `queues` is an object with all my queues.
 ```
const repeatableJobs = await queues.syncCommitsQueue.getRepeatableJobs();

  if (repeatableJobs.length > 0) {
    console.log('Current repeatable configs: ', repeatableJobs);

    repeatableJobs.forEach(async job => {
      await queues.syncCommitsQueue.removeRepeatableByKey(job.key);
    });
  }

**Comment by ganeshcse2991** [comment]
@eltronix  `taskQueue.removeRepeatableByKey(jobs[0].key);` this is how I am also trying. Its saying `removeRepeatableByKey` is not a function

**Comment by eltronix** [comment]
@ganeshcse2991 what version are you using?

**Comment by ganeshcse2991** [comment]
@eltronix `version - "bull": "^3.4.4",`

**Comment by eltronix** [comment]
> @eltronix https://github.com/OptimalBits/bull/blob/develop/test/test_repeat.js#L362

@manast That's for a named repeatable job. What if it isn't named, would it still work?

**Comment by eltronix** [comment]
@ganeshcse2991 I'm using `"bull": "^3.7.0"`
Try upgrading to that.

You can also try using `removeRepeatable` with a **named** repeatable job as demonstrated here:
https://github.com/OptimalBits/bull/blob/develop/test/test_repeat.js#L362

**Comment by ganeshcse2991** [comment]
@manast I am able to remove the repeatable job now. The problem was i am adding the job to the queue with: 

```
let jobOptions = {
        priority: queue_options.priority,
        repeat: { cron: '0 47 6 * * 4' },
        attempts: 3,
        removeOnComplete: true,
        jobId: queue_options.job_id,
        backoff: 3,
        timeout: 60000,
      };
      taskQueue.add('task', queue_options.data, jobOptions);
```
And trying to remove the job like:

```
let job = await taskQueue.removeRepeatable('task', {cron : '0 47 6 * * 4'});
```

I fixed it by passing the jobOptions and i was able to successfully remove the job from the queue.

```
let job = await taskQueue.removeRepeatable('task' jobOptions);
```

IMO why should i even pass the entire job options to remove the job from the queue. Should'nt jobId and cron be enough to remove it?  It will be tough to pass jobOptions that was used while creating the job to the function that is deleting the job from the queue. 

Life would be simpler if you could provide us a method where we can just delete the repeatable jobs too with 

```
queue.removeJob(customJobId);
```

**Comment by stevenolay** [comment]
@ganeshcse2991 ganeshcse2991. 

If you are using TypeScript it’s important to note the type definition for removeReoeatavleJobByKey is not exposed. You can get around this by doing:

taskQueue[‘removeRepeatableJobByKey’]. This works because it’s at least defined on the queue prototype and is there on the insta fisted instance of the Queue.

**Comment by nandofalcao** [comment]
I did it with:

```
queue.removeRepeatable('nameOfProcess', { cron: cronValueUsedOnAdd });
```

The second parameter is one repeat options and not the job options.

**Comment by KonstantinKudelko** [comment]
Guys I have a problems with removing a repeatable jobs.

I want replace the previous job in new one. For this I remove the job like:
```
export const deleteReminder = async () => {
  const repeatableJobs = await needsQueue.getRepeatableJobs();

  repeatableJobs.forEach(async job => await needsQueue.removeRepeatableByKey(job.key));
};
```
As I see on the console, it works. But when I check the redis I see that records wasn't remove. Is it command also removes the job from the Redis? Cause I still see that old jobs are called =|

**Comment by stansv** [comment]
@KonstantinKudelko https://github.com/OptimalBits/bull/issues/1277#issuecomment-534939664

Example —

```
  public removeAllRepeatable = async (): Promise<void> => {
    const queue = await this.queue;
    const jobs = await queue.getRepeatableJobs();
    for (let i = 0; i < jobs.length; i++) {
      const job = jobs[i];
      await queue.removeRepeatable({ cron: job.cron, jobId: job.id });
    }
  };
```

**Comment by zivaricha** [comment]
> @KonstantinKudelko [#1277 (comment)](https://github.com/OptimalBits/bull/issues/1277#issuecomment-534939664)
> 
> Example —
> 
> ```
>   public removeAllRepeatable = async (): Promise<void> => {
>     const queue = await this.queue;
>     const jobs = await queue.getRepeatableJobs();
>     for (let i = 0; i < jobs.length; i++) {
>       const job = jobs[i];
>       await queue.removeRepeatable({ cron: job.cron, jobId: job.id });
>     }
>   };
> ```

will this kill active jobs aswell?
i.e: lets say i have a repeated job that scheduled to run every 5 minutes, i than i want to change it to every 10 minutes.
lets say that at time of deployment, there is an active repeated job X (of the 5 minute type)
and on deployment i remove all existing repeated jobs of that queue (as your code suggests)
will this kill the active job X also?
how can i make sure that active jobs are awaited before i kill the repeated jobs?

**Comment by apmcodes** [comment]
Been trying to delete the repeatable job, but unable to do so. Tried the various suggestion from this thread. 

`
await workerPrb.removeRepeatable({ repeat: repeatOpts, jobId: job.id })
`

**Comment by younes-io** [comment]
Why is it so hard to remove a repeatable job ?? I tried all suggested solutions here, and none of them worked. I'm using the latest version of the library..

**Comment by mydylan** [comment]
@younes-io Same for me. Already spent few days but without success. Nothing are working for me.

**Comment by manast** [comment]
Can you post an example where the remove fails?

**Comment by Xairoo** [comment]
It's also not working for me. Have tested BullMQ too.

```
const Queue = require("bull");
const queue = new Queue("test")

queue.add(
  "foo",
  {},
  {
    jobId: "bar",
    repeat: { every: 1000 },
  }
);

setTimeout(() => {
  queue.removeRepeatable("foo", {
    jobId: "bar",
    repeat: { every: 5000 },
  });
}, 10000);
```

**Comment by fairmutex** [comment]
Seems like you only need name and cron value, worked on "bull":"^4.1.4",

```
        queue.add("myTaskName",{data1:'Foo', data2:'Bar'}, { repeat: { cron: "*/2 * * * *" } })
        .then((job) => {
          queue.removeRepeatableByKey("myTaskName::::*/2 * * * *");
        });
```

**Comment by manast** [comment]
Reopening since it could be the case that it is not working properly using "every".

**Comment by Xairoo** [comment]
`removeRepeatableByKey` is an option to remove a job with `every` because the `key` looks like `"every:::1000"` or with given jobId `"every:yourJobId::1000"`

```js
const Queue = require("bull");
const queue = new Queue("test");

(async () => {
  await queue.obliterate({ force: true });

  queue.add(
    "myTaskName",
    { data1: "Foo", data2: "Bar" },
    { repeat: { cron: "*/1 * * * *" } }
  );

  queue.add(
    "every",
    { data1: "Foo", data2: "Bar" },
    {
      jobId: "bar", // Comment to test it without a jobId
      repeat: { every: 1000 },
    }
  );

  setTimeout(() => {
    console.log("remove...");
    // Works
    queue.removeRepeatableByKey("myTaskName::::*/1 * * * *");

    // Doesn't work
    queue.removeRepeatable(
      "every",
      { data1: "Foo", data2: "Bar" },
      {
        jobId: "bar", //
        repeat: { every: 1000 },
      }
    );

    // Works when jobId is not set
    queue.removeRepeatableByKey("every:::1000");

    // Works with jobId
    queue.removeRepeatableByKey("every:bar::1000");
  }, 5000);

  setInterval(async () => {
    const jobs = await queue.getJobs();
    jobs.forEach((job) => {
      console.log("job:", job.name);
    });
  }, 1000);
})();

```

**Comment by younes-io** [comment]
I removed it like this `await queue.removeRepeatable({ cron: cronValue });`

**Comment by kagai** [comment]
@younes-io what is the cronValue, is it the cron string ? if so what if you have two repeatable jobs with the same cronValue?

**Comment by younes-io** [comment]
> @younes-io what is the cronValue, is it the cron string ? if so what if you have two repeatable jobs with the same cronValue?

Yes, it's the cron string.
I haven't tested the case of two repeatable jobs with the same value.

**Comment by ceroy-ak** [comment]
Hi. I have a use case where I have multiple calls running using Exotel and the process has to poll the Exotel API every minute to get the status of the call and based on that proceed further. Now the problem is that once a call complete I have to stop that repeatable job. So how should I do it? Like what should be the key to stop that particular repeatable job from inside process

**Comment by nachpav** [comment]
Hello!
Please tell me how to get the key of a repeatable job? job.toKey() retruns same values for different tasks -  bull:scheduledProcs:undefined

**Comment by emcodest** [comment]
If you are using a recent version, you can do:  
Tested on bull 4.16.3
 
```
const Queue = require('bull')  

const queue = new Queue(queue_name_x, {
        redis: {
            host: '127.0.0.1',
            port: 6379
        }
    })  


const job_key = job.opts.repeat.key // job is the object from queue.process(async (job) => { })  

const job_cron = job.opts.repeat.cron  


try{

await queue.removeRepeatableByKey(job_key, { cron: job_cron, jobId: job.id}) // Optional if you specified a jobId when adding


}catch(ex){

}

```
