### ISSUE TITLE
Jobs stuck

### ISSUE THREAD

**Issue by gmarcz** [OptimalBits/bull#109]
Sometime I got an error like this:

```javascript
2015-03-12 14:45:01.159: Possibly unhandled SyntaxError: Unexpected token u
    at Object.parse (native)
    at Function.Job.fromData (/src/node_modules/bull/lib/job.js:268:40)
    at /src/node_modules/bull/lib/job.js:37:18
    at tryCatch1 (/src/node_modules/bull/node_modules/bluebird/js/main/util.js:45:21)
    at Promise$_callHandler [as _callHandler] (/src/node_modules/bull/node_modules/bluebird/js/main/promise.js:660:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/src/node_modules/bull/node_modules/bluebird/js/main/promise.js:675:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (/src/node_modules/bull/node_modules/bluebird/js/main/promise.js:845:14)
    at Promise$_settlePromises [as _settlePromises] (/src/node_modules/bull/node_modules/bluebird/js/main/promise.js:988:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/src/node_modules/bull/node_modules/bluebird/js/main/async.js:77:12)
    at Async$consumeFunctionBuffer (/src/node_modules/bull/node_modules/bluebird/js/main/async.js:40:14)
    at process._tickCallback (node.js:419:13)
    at Async.Promise$_Scheduler [as _schedule] (/src/node_modules/bull/node_modules/bluebird/js/main/schedule.js:30:17)
    at Async$_queue [as _queueTick] (/src/node_modules/bull/node_modules/bluebird/js/main/async.js:103:14)
    at Async$invoke [as invoke] (/src/node_modules/bull/node_modules/bluebird/js/main/async.js:67:10)
    at Promise$_fulfillUnchecked [as _fulfillUnchecked] (/src/node_modules/bull/node_modules/bluebird/js/main/promise.js:943:15)
    at Promise$_fulfill [as _fulfill] (/src/node_modules/bull/node_modules/bluebird/js/main/promise.js:826:10)
    at PromiseResolver$_callback (/src/node_modules/bull/node_modules/bluebird/js/main/promise_resolver.js:63:21)
    at try_callback (/src/node_modules/bull/node_modules/redis/index.js:579:9)
    at RedisClient.return_reply (/src/node_modules/bull/node_modules/redis/index.js:664:13)
    at ReplyParser.<anonymous> (/src/node_modules/bull/node_modules/redis/index.js:312:14)
    at ReplyParser.emit (events.js:95:17)
    at ReplyParser.send_reply (/src/node_modules/bull/node_modules/redis/lib/parser/javascript.js:300:10)
    at ReplyParser.execute (/src/node_modules/bull/node_modules/redis/lib/parser/javascript.js:211:22)
    at RedisClient.on_data (/src/node_modules/bull/node_modules/redis/index.js:535:27)
```
When I check the parameters for Job.fromData = function(queue, jobId, data)
the data is just this: { delay: '0' }

Maybe this problem is related to this action that onCompleted event I requeue some jobs like this:
job.queue.add(job.data, {delay: delay_time});

**Comment by albertjan** [comment]
Seems related to: https://github.com/OptimalBits/bull/issues/90

**Comment by lchenay** [comment]
What version of bull do you use ? #90 is closed and i have never see this bug again.

**Comment by gmarcz** [comment]
It happened with 0.2.3.
I will check the other issue, maybe I can find out what is the root cause of this.

**Comment by manast** [comment]
I have upgraded to the latest node_redis but there are some tests failing so I am fixing them now. I hope to have it ready today.

**Comment by manast** [comment]
I just release v0.2.5. Let me know if jobs get stuck after this update.

**Comment by gmarcz** [comment]
I still see this error:

```javascript
Possibly unhandled SyntaxError: Unexpected token u
    at Object.parse (native)
    at Function.Job.fromData (/src/node_modules/bull/lib/job.js:271:40)
    at /src/node_modules/bull/lib/job.js:39:18
    at tryCatch1 (/src/node_modules/bull/node_modules/bluebird/js/main/util.js:45:21)
    at Promise$_callHandler [as _callHandler] (/src/node_modules/bull/node_modules/bluebird/js/main/promise.js:660:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/src/node_modules/bull/node_modules/bluebird/js/main/promise.js:675:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (/src/node_modules/bull/node_modules/bluebird/js/main/promise.js:845:14)
    at Promise$_settlePromises [as _settlePromises] (/src/node_modules/bull/node_modules/bluebird/js/main/promise.js:988:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/src/node_modules/bull/node_modules/bluebird/js/main/async.js:77:12)
    at Async$consumeFunctionBuffer (/src/node_modules/bull/node_modules/bluebird/js/main/async.js:40:14)
    at Async.Promise$_Scheduler [as _schedule] (/src/node_modules/bull/node_modules/bluebird/js/main/schedule.js:30:17)
    at Async$_queue [as _queueTick] (/src/node_modules/bull/node_modules/bluebird/js/main/async.js:103:14)
    at Async$invoke [as invoke] (/src/node_modules/bull/node_modules/bluebird/js/main/async.js:67:10)
    at Promise$_fulfillUnchecked [as _fulfillUnchecked] (/src/node_modules/bull/node_modules/bluebird/js/main/promise.js:943:15)
    at Promise$_fulfill [as _fulfill] (/src/node_modules/bull/node_modules/bluebird/js/main/promise.js:826:10)
    at PromiseResolver$_callback (/src/node_modules/bull/node_modules/bluebird/js/main/promise_resolver.js:63:21)
    at /src/node_modules/bull/node_modules/redis/index.js:1210:13
    at try_callback (/src/node_modules/bull/node_modules/redis/index.js:592:9)
    at RedisClient.return_reply (/src/node_modules/bull/node_modules/redis/index.js:685:13)
    at ReplyParser.<anonymous> (/src/node_modules/bull/node_modules/redis/index.js:321:14)
```
and the job data is just { delay="0"}

**Comment by manast** [comment]
It seems as this happens often to you. Can you possibly create a test case that reproduces it or provide some more information?

**Comment by gmarcz** [comment]
I tried to write a small app but the problem did not come up.
I think that it is related to the delay, but could not catch it yet.

**Comment by gmarcz** [comment]
I still could not regenerate the problem, but what I see is we have a docker what runs the queue and when we deploy (docker restart) then sometimes this error happens.

**Comment by manast** [comment]
I think this issue may then be related to #103 I will work on a fix for this as soon as I have some time.

**Comment by manast** [comment]
Issue #103 has been fixed and released so you could check if this resolves your problem.

**Comment by albertjan** [comment]
Awesome! You also fixed the stalled jobs without a restart issue! Thanks! @remkoboschker you'll like this too :smile:

**Comment by gmarcz** [comment]
Thank you, I will test it.

**Comment by gmarcz** [comment]
Something else causing thins problem, because I still see it in the log, and after it happens that queue is stuck, it is now processing any jobs.

```javascript
2015-03-23 14:01:26.065: Possibly unhandled SyntaxError: Unexpected token u
    at Object.parse (native)
    at Function.Job.fromData (/src/node_modules/bull/lib/job.js:271:40)
    at /src/node_modules/bull/lib/job.js:39:18
    at tryCatch1 (/src/node_modules/bull/node_modules/bluebird/js/main/util.js:45:21)
    at Promise$_callHandler [as _callHandler] (/src/node_modules/bull/node_modules/bluebird/js/main/promise.js:660:13)
    at Promise$_settlePromiseFromHandler [as _settlePromiseFromHandler] (/src/node_modules/bull/node_modules/bluebird/js/main/promise.js:675:18)
    at Promise$_settlePromiseAt [as _settlePromiseAt] (/src/node_modules/bull/node_modules/bluebird/js/main/promise.js:845:14)
    at Promise$_settlePromises [as _settlePromises] (/src/node_modules/bull/node_modules/bluebird/js/main/promise.js:988:14)
    at Async$_consumeFunctionBuffer [as _consumeFunctionBuffer] (/src/node_modules/bull/node_modules/bluebird/js/main/async.js:77:12)
    at Async$consumeFunctionBuffer (/src/node_modules/bull/node_modules/bluebird/js/main/async.js:40:14)
    at Async.Promise$_Scheduler [as _schedule] (/src/node_modules/bull/node_modules/bluebird/js/main/schedule.js:30:17)
    at Async$_queue [as _queueTick] (/src/node_modules/bull/node_modules/bluebird/js/main/async.js:103:14)
    at Async$invoke [as invoke] (/src/node_modules/bull/node_modules/bluebird/js/main/async.js:67:10)
    at Promise$_fulfillUnchecked [as _fulfillUnchecked] (/src/node_modules/bull/node_modules/bluebird/js/main/promise.js:943:15)
    at Promise$_fulfill [as _fulfill] (/src/node_modules/bull/node_modules/bluebird/js/main/promise.js:826:10)
    at PromiseResolver$_callback (/src/node_modules/bull/node_modules/bluebird/js/main/promise_resolver.js:63:21)
    at try_callback (/src/node_modules/bull/node_modules/redis/index.js:592:9)
    at RedisClient.return_reply (/src/node_modules/bull/node_modules/redis/index.js:685:13)
```

**Comment by manast** [comment]
Could it be that when you call this: 
```job.queue.add(job.data, {delay: delay_time});``` job.data is for some reason already corrupt?
you could make a few checks on the job.data object before calling queue.add in order to catch any possible inconsistencies.

**Comment by manast** [comment]
Although we do not know why the job retrieved is corrupted the queue should not get stucked, so as an initial fix I keep processing the queue even after this error appears. Could you please check in the latest version 0.2.7 that the queue continues processing jobs even after this error?

**Comment by lchenay** [comment]
This bug still happen in 0.2.7 (bfa32eccf4db86fe2d3018c5df45e5cb10efdf85)

**Comment by manast** [comment]
I don't think this issue happens anymore, so please reopen if needed.

**Comment by jsarenik** [comment]
Could it be that this issue was related to {{node}} {{0.10}} being obsoleted? So far I see this issue appearing only with {{bull-1.0.0-rc1}} running on {{node 0.10.40}} whereas I have experimented with running the same application with {{bull}} upgraded to {{1.1.3}} and {{node v5.9.1}}. Thanks.

And thank you for continued work on bull!
