### ISSUE TITLE
MaxListenersExceededWarning caused by Sandbox.js

### ISSUE THREAD

**Issue by zlafil** [OptimalBits/bull#1179]
Bull version: 3.5.2

It seems that sandbox.js never removes the listener for the exit event. This causes the MaxListenersExceededWarning to be shown in Node.

https://github.com/OptimalBits/bull/blob/develop/lib/process/sandbox.js#L36

Example in TypeScript
```javascript
 const queue = new Bull("Queue", { redis: { port: Config.config.redisPort, host: Config.config.redisHost } });
  queue.process(1, "pathToWorker.js");
  for (let i = 0; i < 12; i++) {
    queue.add("");
  }
```

Adding 
```javascript
child.removeListener('exit');
````
before this line https://github.com/OptimalBits/bull/blob/develop/lib/process/sandbox.js#L41 seems to solve the problem

**Comment by manast** [comment]
Should not be needed, events are removed when jobs are completed or failed. Do you have a test case where this is not the case?

**Comment by zlafil** [comment]
Hi

If you run my example you will se that you get the warning MaxListenersExceededWarning.
In the file Sandbox.js you take care of the evenListener for 'message' by removing it on completed, failed and error but nowhere do you remove the listener for the 'exit' event.

**Comment by manast** [comment]
@zlafil it is not removed from the exit event because it is not needed.

**Comment by MarshalW** [comment]
@zlafil, This is not possible, will cause the node process to increase.
```js
child.removeListener('exit');
```

@manast, This may be a problem. Before this line: https://github.com/OptimalBits/bull/blob/develop/lib/process/sandbox.js#L42, add:

```js
console.log(child.listenerCount('exit'));
```
When processed continuously，`listenerCount` increasing.

The problem may be in `sandbox.js`，child remove  message listener (`child.removeListener('message', handler);`), but not remove exit listener.

I tried to modify it in the generated javascript code：

```js
'use strict';

var Promise = require('bluebird');

module.exports = function(processFile, childPool) {
  return function process(job) {
    console.log('return process(job)');
    return childPool.retain(processFile).then(function(child) {
      child.send({
        cmd: 'start',
        job: job
      });

      // added code
      function exitHandler(exitCode){
        reject(new Error('Unexpected exit code: ' + exitCode));
      }

      var done = new Promise(function(resolve, reject) {
        function handler(msg) {
          switch (msg.cmd) {
            case 'completed':
              child.removeListener('message', handler);
              resolve(msg.value);
              break;
            case 'failed':
            case 'error':
              child.removeListener('message', handler);
              var err = new Error();
              Object.assign(err, msg.value);  
              reject(err);
              break;
            case 'progress':
              job.progress(msg.value);
              break;
          }
        }

        child.on('message', handler);
        child.on('exit', exitHandler); // modified
      });

      return done.finally(function() {
        child.removeListener('exit',exitHandler); // added code
        console.log(child.listenerCount('exit'));
        childPool.release(child);
      });
    });
  };
};

```
The problem has been solved.

Looking forward to the final resolution of this problem. Thank you manast.

**Comment by zlafil** [comment]
Hi,

Sorry for the unclear description and solution.
I was a little to quick writing my fix. I realized the exit handler was the problem using --trace-warnings in node which gave me

```javascript
(node:22736) MaxListenersExceededWarning: Possible EventEmitter memory leak detected. 11 exit listeners added. Use emitter.setMaxListeners() to increase limit
[server]     at _addListener (events.js:243:17)
[server]     at ChildProcess.addListener (events.js:259:10)
  at C:\GitRoot\promaster-edit\node_modules\bull\lib\process\sandbox.js:34:15
[server]     at PROJECT\node_modules\bull\lib\process\sandbox.js:34:15
```

This pointed me to the line:  

```javascript
child.on('exit', function (exitCode) {
          reject(new Error('Unexpected exit code: ' + exitCode));
        });
```
I have tested your solution and it works as expected, the MaxListenersExceededWarning is not shown any more

**Comment by manast** [comment]
@MarshalW good catch!. I am working on a PR with the fix.

**Comment by Jujunol** [comment]
Was this patched? I'm still experiencing the issue

app.js
```
const app = require('express')();
const Queue = require('bull');

const example = new Queue('example');

example.process(1, __dirname + '/processors/callback');

for (let i = 0; i < 100; i++ ) {
    example.add("");
}
```

callback.js
```
module.exports = function (job, done) {
    done();
}
```
