### ISSUE TITLE
`enableReadyCheck`/`maxRetriesPerRequest` issues after upgrading to >4.6.2

### ISSUE THREAD

**Issue by schw4rzlicht** [OptimalBits/bull#2347]
## Description

We are using bull with https://github.com/nestjs/bull and wanted to upgrade from bull ~4.5.0 to ~4.8.0.
When doing so, we encounter `enableReadyCheck` and `maxRetriesPerRequest` again which we thought we solved (and we're still pretty sure we did), also see https://github.com/OptimalBits/bull/issues/2216.

This time, I suspect 4.6.2 (https://github.com/OptimalBits/bull/commit/d3b91386e30d7205efdc19bcd18fe1e5fefa3542) to be the issue since that commit changed handling of mentioned properties.

As I said in https://github.com/OptimalBits/bull/issues/2216#issuecomment-973179028, we messed up initializing the bull module at the time but fixed it, see below.

## Minimal, Working Test code to reproduce the issue.

```typescript
BullModule.forRootAsync({
    imports: [RedisModule],
    inject: [RedisProvider],
    useFactory: (redisProvider: RedisProvider) => ({
        createClient: (type, redisOpts) => {
            switch (type) {
                case "subscriber":
                    return new IORedis({
                        ...redisOpts,
                        host: redisHost,
                        port: redisPort,
                        commandTimeout: 2000,
                    });
                default:
                    return new IORedis.Cluster([{ host: redisHost, port: redisPort }], {
                        slotsRefreshTimeout: 2000,
                        enableReadyCheck: false,
                        redisOptions: redisOpts,
                    });
            }
        },
    }),
});
```

## Bull version

4.5.1 ✅ → 4.6.2 ❌ → 4.8.0 ❌

## Additional information

We are on IORedis 4.28.5 [as spec'ed by bull's `package.json`](https://github.com/OptimalBits/bull/blob/933896aef06935d5f6bd4e608d6f266f904c6976/package.json#L26).

One question about that: Are you considering to migrate to 5.x soon?

**Comment by manast** [comment]
What are the issues?

**Comment by manast** [comment]
In any case, I suspect that you are not setting "maxRetriesPerRequest: null" on you subscriber and bclient redis connections (as the warning should be telling you).

**Comment by schw4rzlicht** [comment]
> What are the issues?

Sorry, forgot that: We are getting 

```
Using a redis instance with enableReadyCheck or maxRetriesPerRequest for bclient/subscriber is not permitted.
   see https://github.com/OptimalBits/bull/issues/1873
```

during runtime.

> In any case, I suspect that you are not setting "maxRetriesPerRequest: null" on your subscriber and bclient redis connections (as the warning should be telling you).

And that's true, because we never did. Before 4.6.2 that was fine, I suspect that bull did that by itself when using `createClient()` through `redisOpts`. If that's the case, 4.6.2 introduces a breaking change and should have increased the major version imo 🤔

> Btw, whatever the issue, it would be better if you can isolate it in a smaller test case, there should not be the need for something like RedisProvider to reproduce the issue.

Yep, you're right, simplified my example.

**Comment by manast** [comment]
> And that's true, because we never did. Before 4.6.2 that was fine, I suspect that bull did that by itself when using `createClient()` through `redisOpts`. If that's the case, 4.6.2 introduces a breaking change and should have increased the major version imo 🤔

No, if you provide an external Redis instance Bull did not change it, so this was not a breaking change but a bugfix.

**Comment by iwaduarte** [comment]
We are facing the same kind of issues. Since the upgrade, we are creating empty jobs inside the queue and getting this same error.

"Reached the max retries per request limit (which is 20). Refer to "maxRetriesPerRequest" option for details."

**Comment by manast** [comment]
@iwaduarte that error does not come from Bull but from ioredis. Your connection failed and it tried 20 times to perform some command until it gave up.

**Comment by schw4rzlicht** [comment]
> > And that's true, because we never did. Before 4.6.2 that was fine, I suspect that bull did that by itself when using `createClient()` through `redisOpts`. If that's the case, 4.6.2 introduces a breaking change and should have increased the major version imo 🤔
> 
> No, if you provided an external Redis instance Bull did not change it, so this was not a breaking change but a bugfix.

But we are not providing an "external Redis instance", we let Bull create one when needed using `createClient`. With Redis options coming from Bull and passed on to the appropriate constructors/factories. I also don't really see a difference to the documentation here: https://docs.bullmq.io/bull/patterns/reusing-redis-connections

That mechanism worked previously to 4.6.2 so I don't really see how this is a bug*fix* or a non-breaking change in behavior 🤔

**Comment by manast** [comment]
All I can say is that we have not intended to make a breaking change, and still I am not sure this is the case. Aren't you getting any warning when instantiating the Queues?

**Comment by TheBeachMaster** [comment]
I ran into this issue when I followed [this guide](https://docs.bullmq.io/bull/patterns/reusing-redis-connections)  on reusing connections.

After viewing https://github.com/OptimalBits/bull/issues/1873  and https://github.com/luin/ioredis/issues/1285 I managed to get past this error by doing the following

I set my ioredis connection options as follows:

```json
{
  tls: null,
  lazyConnect: false,
  showFriendlyErrorStack: true,
  maxRetriesPerRequest: null,
  enableReadyCheck: false
}
```

What's important here is 

```
  maxRetriesPerRequest: null,
  enableReadyCheck: false
```

Why? See default ioredis config [here](https://luin.github.io/ioredis/interfaces/CommonRedisOptions.html#enableReadyCheck) and [here](https://luin.github.io/ioredis/interfaces/CommonRedisOptions.html#maxRetriesPerRequest) hence the error.

For the curious here's how my shared connection looks like

```js
import * as Redis from "ioredis";
import * as Queue from "bull";
import { redisUrl } from "config";
import { RedisUtil } from "redisutil";

const connOpts = new RedisUtil().connOpts // These are the connection options above, you can just put them here. The connection config is shared with another client that uses the same Redis instance in my case

let client;
let subscriber;


const opts = {
  createClient: function (type) {
    switch (type) {
      case 'client':
        if (!client) {
          client = new Redis(redisUrl, connOpts);
        }
        return client;
      case 'subscriber':
        if (!subscriber) {
          subscriber = new Redis(redisUrl, connOpts);
        }
        return subscriber;
      case 'bclient':
        return new Redis(redisUrl, connOpts);
      default:
        throw new Error(`Unexpected connection type: ${type}`);
    }
  }
}


export const mainQueue = Queue("my_queue", opts)
```  

I'm running bull `v4.8.1`

**Comment by schw4rzlicht** [comment]
We fixed the issue adding `maxRetriesPerRequest = null` to the `redisOpts` that we get as param from bull in `createClient()`.

**Comment by calvin-summer** [comment]
> @TheBeachMaster I would recommend setting maxRetriesPerRequest to a small value for the "client" connection, i.e. the one used by Queue##add(), so that you get an error instead of potentially hanging forever.

hey, do you mind explaining what exactly would "hang forever" if we use `maxRetriesPerRequest: null`? as in, would establishing redis connection hang? or would a job hang?

**Comment by manast** [comment]
@calvin-summer since it will never fail and retry forever the call to "add" could potentially hang forever.

**Comment by calvin-summer** [comment]
> @calvin-summer since it will never fail and retry forever the call to "add" could potentially hang forever.

thanks for the insight 🙇‍♂️

**Comment by raghavbitqit** [comment]
RedisOption {
  enableReadyCheck: false,
  port: 6379,
  host: '127.0.0.1',
  db: undefined,
  retryStrategy: [Function: retryStrategy]
} After printing redisOpts of createClient I am getting this there is maxRetriesPerRequest: null and I am still getting this error , I have to remove redisOpts and passed this parameter explicitily that only it is working , and  doing so it will after the reusing redis connection concept
