### ISSUE TITLE
Delivery Guarantees

### ISSUE THREAD

**Issue by defunctzombie** [OptimalBits/bull#303]
Apologies if this is documented and I was unable to find it. What delivery pattern does this library aim for? At most once? At least once? Something else?

I am seeing jobs appear more than once into my process workers even tho concurrency is set to 1 (and I haven't finished the previous job). So am wondering if I should expect that given the delivery goals of this library.

**Comment by manast** [comment]
At most once. It could happen that the worker processing a job has locked the event loop, which would free the lock on the job he is processing and then other workers might pick that job thinking it has been stalled.

**Comment by defunctzombie** [comment]
In my case I only have 1 worker, but yes, I do have something in that worker (a c++ binding) that locks the loop. Will change that to be async. Thanks for clearing that up.

Maybe document this somewhere and the little tip about workers locking the event loop which to me was non-obvious.

**Comment by manast** [comment]
yes, we have had this reported several times. I thought it was obvious but clearly it was not :)

**Comment by defunctzombie** [comment]
In this case I actually had a js file for workers for two queues. And one of them was the one that would lock up the event loop for the whole process for a bit. This I guess caused the lock free-ing behavior. Is there a way to set a longer lock free timeout? I see references to `LOCK_RENEW_TIME` is that just an env var or per queue setting I can configure?

**Comment by manast** [comment]
fixed in 0ca6ba8b2c2d51c7b2ee04ab2a60756a31f0cb33

**Comment by manast** [comment]
Regarding renew time, This has also been discussed some time ago. There is not reason to have it configurable.

**Comment by defunctzombie** [comment]
👍 Cool. Closing this as my particular question and issue has been resolved. I will see if changing to async for my binding helps this delivery issue or what else I can do to avoid receiving the job again.

**Comment by defunctzombie** [comment]
Adding here that even tho I am no longer blocking the event loop, I still see my single worker getting the same job again even tho it is currently working on a job :(

**Comment by defunctzombie** [comment]
Is there some sort of implicit timeout or other thing happening? My workers take some time to process their jobs but they are not stalled.
